# Generated by Django 5.0.3 on 2024-05-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
