# Generated by Django 5.0.3 on 2024-05-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
