# Generated by Django 5.0.3 on 2024-05-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_age_customuser_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite',
            field=models.CharField(max_length=200),
        ),
    ]
