# Generated by Django 3.2.25 on 2024-05-02 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240409_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hashtang',
            new_name='hashtag',
        ),
    ]
